### ISSUE TITLE
Please don't use footnote links when generating release notes

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/relnotes#102]
When pruning the generated list of merged PRs, it's painful to keep the list of PRs and the list of links in sync. I think we should generate normal links, rather than footnote links, making it easy to curate the list.

I don't think this will make the release notes any less readable; the links aren't long, and the rendered version will look identical.

**Comment by Mark-Simulacrum** [comment]
FWIW, I have some local scripts that automatically prune the footnote links as needed. It's worth considering just not using them though.

**Comment by joshtriplett** [comment]
https://github.com/rust-lang/relnotes/pull/103
